routes/web.php
<?php

use App\Http\Controllers\CustomersController;
use App\Http\Controllers\TambonController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::redirect('/', 'index');

Route::get('index/', [CustomersController::class, 'index'])->name('app');
Route::get('register/', [CustomersController::class, 'register'])->name('register');
Route::get('success/', [CustomersController::class, 'success'])->name('success');
Route::get('list/menagement', [CustomersController::class, 'customers'])->name('customers.menagement');
Route::get('getCustomersList/', [CustomersController::class, 'getCustomersList'])->name('customers.getCustomersList');


Route::post('check-traking', [CustomersController::class, 'checkTracking'])->name('checkTracking');
Route::post('check-phone', [CustomersController::class, 'checkPhone'])->name('checkPhone');

Route::post('customers/getCustomersList', [CustomersController::class, 'getCustomersList'])->name('customers.getCustomersList');
Route::put('/update/{id}','CustomersController@update')->name('customers.update');
Route::get('/customers/delete/{id}', [CustomersController::class, 'customersDelete']);
Route::get('customers/export/', [CustomersController::class, 'export'])->name('export');
Route::post('customers/import/', [CustomersController::class, 'import'])->name('import');
Route::get('customers/zip/', [CustomersController::class, 'downloadZip'])->name('zip');

Route::post('/config/update',[CustomersController::class, 'configUpdate'])->name('config.update');

Route::resource('customers',CustomersController::class);

Route::get('/provinces', [TambonController::class, 'getProvinces'])->name('getProvinces');
Route::get('/province/{province_code}/amphoes', [TambonController::class, 'getAmphoes'])->name('getAmphoes');
Route::get('/province/{province_code}/amphoe/{amphoe_code}/tambons', [TambonController::class, 'getTambons'])->name('getTambons');
Route::get('/province/{province_code}/amphoe/{amphoe_code}/tambon/{tambon_code}/zipcodes', [TambonController::class, 'getZipcodes'])->name('getZipcodes');

app/Models/Customers.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{

    use HasFactory;

    /**
     * @var array
     */

    protected $table = 'customers';

    protected $fillable = [
        'fullname',
        'address', 'province',
         'amphoe', 'tambon', 'zipcode',
          'phone', 'age', 'sex', 'medianews', 'medianews_other', 'tracking', 'created_at', 'updated_at'
    ];
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\Exports\CustomersExport;
use App\Imports\CustomersImport;
use App\Models\Config;
use App\Models\Customers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Validator;
use DB;
use Illuminate\Support\Facades\Redirect;
use Maatwebsite\Excel\Facades\Excel;
use File;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

class CustomersController extends Controller
{

    public function index()
    {
        $count = DB::table('customers')->count();
        $config =  DB::table('config')->first();

        return view('customers.app', compact('count', 'config'));
    }
    public function listItems()
    {
        return  [
            'age' => [
                "น้อยกว่า 13 ปี",
                "14 - 18 ปี",
                "19 - 23 ปี",
                "24 - 29 ปี",
                "30 ปีขึ้นไป",
            ],
            'sex' => [
                "ชาย",
                "หญิง",
                "ไม่ระบุ",
            ],
            'media' => [
                "Facebook",
                "Youtube",
                "Tiktok",
                "Link",
                "อื่นๆ",
            ]
        ];
    }

    public function register()
    {
        $items = $this->listItems();
        // dump($items['sex']);
        // exit();
        // return view('customers.register',compact('items'));
        return View::make('customers.register', ['items' => $items]);
    }
    public function store(Request $request)
    {

        $messages =  [

            'fullname.required' => 'กรุณากรอกข้อมูล ชื่อ - นามสกุล',
            'phone.required' => 'กรุณากรอกข้อมูล เบอร์โทร',
            'phone.unique' => 'เบอร์โทรนี้ มีอยู่ในระบบแล้ว!',
            'phone.digits_between' => 'เบอร์โทรไม่ถูกต้อง',
            'address.required' => 'กรุณากรอกข้อมูล ที่อยู่',
            'province.required' => 'กรุณาเลือกจังหวัด',
            'amphoe.required' => 'กรุณาเลือกเขต/อำเภอ',
            'tambon.required' => 'กรุณาเลือกแขวง/ตำบล',
            'age.required' => 'กรุณาเลือกอายุ',
            'sex.required' => 'กรุณาเลือกเพศ',
            'media.required' => 'กรุณาเลือกรู้จักแคมเปญ',


        ];
        $validator = Validator::make(
            $request->all(),
            [
                'fullname' => 'required',
                'phone' => 'required|unique:customers|numeric|digits_between:10,10',
                'address' => 'required',
                'province' => 'required',
                'amphoe' => 'required',
                'tambon' => 'required',
                'age' => 'required',
                'sex' => 'required',
                'media' => 'required',


            ],
            $messages
        );

        if ($request->media == 4 && empty($request->medianews_other)) {
            $message = [
                "medianews_other" => "กรุณากรอก รู้จักแคมเปญนี้จากสื่ออื่น"
            ];
            return redirect()->back()->withErrors($message)->withInput();
        }
        if ($validator->fails()) {
            $message = $validator->errors();
            return redirect()->back()->withErrors($message)->withInput();
        }



        $modelsInsert = [
            'fullname' => $request->fullname,
            'phone' => $request->phone,
            'address' => $request->address,
            'province' => $request->province,
            'amphoe' => $request->amphoe,
            'tambon' =>  $request->tambon,
            'zipcode' =>  $request->zipcode,
            'age' => $request->age,
            'sex' => $request->sex,
            'medianews' => $request->media,
            'medianews_other' => $request->medianews_other,

        ];


        DB::beginTransaction();
        try {
            //add data customers
            $customers = Customers::create($modelsInsert);

            DB::commit();
            return  Redirect::route('success', ['p' => $modelsInsert['fullname']]);
        } catch (\Exception $e) {

            DB::rollback();

            $message = [
                "msgError" => "เกิดข้อผิดพลาดระหว่างการลงทะเบียน โปรดลองใหม่"
            ];
            return redirect()->back()->withErrors($message)->withInput();
        }
    }


    public function success()
    {
        return view('customers.success');
    }


    public function checkTracking(Request $request)
    {

        $data = $request->all();
        if (isset($data) && $data['phone']) {
            $customers = DB::table('customers')->where('phone', $data['phone'])->first();
            if (isset($customers)) {
                return response()->json([
                    'status' => true,
                    'fullname' => $customers->fullname,
                    'phone' => $customers->phone,
                    'tracking' => $customers->tracking,
                ]);
            } else {
                return response()->json([
                    'status' => false,
                ]);
            }
        }
        // exit;
    }

    public function customers()
    {
        $config =  DB::table('config')->first();
        return view('customers.list',compact('config'));
    }

    public function getCustomersList(Request $request)
    {
        // $customers= DB::table('customers')->get();

        if ($request->ajax()) {
            $draw = $_POST['draw'];
            $row = $_POST['start'];
            $rowperpage = $_POST['length']; // Rows display per page
            $columnIndex = $_POST['order'][0]['column']; // Column index
            $columnName = $_POST['columns'][$columnIndex]['data']; // Column name
            $columnSortOrder = $_POST['order'][0]['dir']; // asc or desc
            $searchValue = $_POST['search']['value'];

            // Search 
            $searchQuery = " ";
            if ($searchValue != '') {
                $searchQuery = " 
                and ( 
     c.fullname LIKE '%" . $searchValue . "%' 
	OR c.phone LIKE '%" . $searchValue . "%' 
	OR c.address LIKE '%" . $searchValue . "%' 
	OR c.province LIKE '%" . $searchValue . "%' 
	OR c.amphoe LIKE '%" . $searchValue . "%' 
	OR c.tambon LIKE '%" . $searchValue . "%' 
	OR c.zipcode LIKE '%" . $searchValue . "%'
    )";
            }
            $customers = DB::select(DB::raw("SELECT * FROM customers c WHERE 1 " . $searchQuery . "
        
        order by " . $columnName . " " . $columnSortOrder . "  limit $row,$rowperpage
        "));

            // foreach($customers as& $m){
            //     $m['btnDel'] = '';
            //     $m['btnNote'] = '';
            //     dd($customers);
            // }
            // exit;

            $totalRecords =  DB::table('customers')->count();
            $response = array(
                "draw" => intval($draw),

                "iTotalRecords" => $totalRecords,
                "iTotalDisplayRecords" => $totalRecords,
                "aaData" => $customers
            );
            return json_encode($response);
        }
        //    return response()->json([
        //         'aaData'=>$customers,
        //         "iTotalRecords" => $totalRecords,
        //         "iTotalDisplayRecords" => $totalRecords,
        //     ]);
    }

    public function checkPhone(Request $request)
    {
        if ($request->ajax()) {
            $data = $request->all();
            if (isset($data) && $data['phone']) {
                $customers = DB::table('customers')->where('phone', $data['phone'])->first();
                if (isset($customers)) {
                    return response()->json([
                        'status' => true,
                    ]);
                } else {
                    return response()->json([
                        'status' => false,
                    ]);
                }
            }
        }
    }



    public function edit($id)
    {
        $items = $this->listItems();

        $customers = DB::table('customers')->where('id', $id)->first();
        return view('customers.edit', compact('items', 'customers'));
    }

    public function destroy(Customers $customers)
    {
        $customers->delete();

        return redirect()->route('customers.list')
            ->with('success', 'deleted successfully');
    }


    public function update(Request $request, Customers $customers)
    {
        $messages =  [

            'fullname.required' => 'กรุณากรอกข้อมูล ชื่อ - นามสกุล',
            'phone.required' => 'กรุณากรอกข้อมูล เบอร์โทร',
            // 'phone.unique' => 'เบอร์โทรนี้ มีอยู่ในระบบแล้ว!',
            'phone.digits_between' => 'เบอร์โทรไม่ถูกต้อง',
            'address.required' => 'กรุณากรอกข้อมูล ที่อยู่',
            'province.required' => 'กรุณาเลือกจังหวัด',
            'amphoe.required' => 'กรุณาเลือกเขต/อำเภอ',
            'tambon.required' => 'กรุณาเลือกแขวง/ตำบล',
            'age.required' => 'กรุณาเลือกอายุ',
            'sex.required' => 'กรุณาเลือกเพศ',
            'medianews.required' => 'กรุณาเลือกรู้จักแคมเปญ',


        ];
        $validator = Validator::make(
            $request->all(),
            [
                'fullname' => 'required',
                // 'phone' => 'required',
                'address' => 'required',
                'province' => 'required',
                'amphoe' => 'required',
                'tambon' => 'required',
                'age' => 'required',
                'sex' => 'required',
                'medianews' => 'required',


            ],
            $messages
        );

        if ($request->media == 4 && empty($request->medianews_other)) {
            $message = [
                "medianews_other" => "กรุณากรอก รู้จักแคมเปญนี้จากสื่ออื่น"
            ];
            return redirect()->back()->withErrors($message)->withInput();
        }
        if ($validator->fails()) {
            $message = $validator->errors();
            return redirect()->back()->withErrors($message)->withInput();
        }
        $modelsUpdate = [
            'fullname' => $request->fullname,
            'address' => $request->address,

resources/views/customers/app.blade.php
@extends('layouts.main')

@section('pageTitle')
POPLOVE SS3
@endsection
@section('style')

@endsection

@section('content')
@php 
$limit_register = 0;
$limit_register = (int)$config->limit_register;

@endphp
<div class="container home-container">
    <div class="home-form">
        <div class="mt-5">
            <div class="d-flex justify-content-center align-items-center">
                <img src="{{ url('/img/logo.png') }}" class="img-logo" width="290px">
            </div>
        </div>
        <div class="mt-3 text-center">
            <div class="project-title">POPLOVE SS3</div>
            <div class="project-subdetail mt-1">
                อยากบอกรักใคร ป๊อปทีนส่งของขวัญให้ !!
            </div>
        </div>
        @if($count <= $limit_register) 
        <div class="card-form">
            <button class="btn btn-danger btn-block btn-custom" id="registerBtn">
                <i class="fas fa-heart"></i>
                ส่งของขวัญ ให้กับคนที่คุณรัก <i class="fas fa-heart"></i></button>
        @endif
            <button class="btn btn-outline-traking btn-block btn-custom" id="trakingBtn">ตรวจสอบการรับรางวัล</button>

           
        </div>
        <div class="mt-4">
            <div class="d-flex justify-content-center align-items-center">
                <!-- <div class="sup-text " id="termsAndConditions">เงื่อนไขและข้อตกลงของกิจกรรม</div> -->
            </div>
        </div>
    </div>
    <div class="bubbling-heart">
        <div><i class="fa fa-heart fa-5x"></i></div>
        <div><i class="fa fa-heart fa-5x"></i></div>
        <div><i class="fa fa-heart fa-5x"></i></div>
        <div><i class="fa fa-heart fa-5x"></i></div>
      </div>
</div>





<div class="modal fade" id="checkTraking" data-backdrop="static" data-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content" id="modal-warning-content">
            <div class="modal-body ">
                <div class="text-center login-title-box">
                    <h4 class="">ตรวจสอบเลข Tracking</h4>
                    <button type="button" class="close close-modal-btn" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-10" id="formResult">
                        <div class="text-center h5">
                            <p id="resultName"></p>
                            <p id="resultPhone"></p>
                            <div id="resultTracking" class=""></div>
                        </div>

                    </div>
                    <div class="col-md-10" id="formCheck">
                        <div class="text-center text-danger h5" id="resultFail"></div>
                        <div class="form-group">
                            <label for="usernameInput" class="font-weight-bold text-color-pink-1">เบอร์โทร</label>
                            <input type="tel" name="phone" id="phoneTracking" class="form-control text-lg"
                                oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1');"
                                style="font-size: 20px;" maxlength="10">
                        </div>
                        <div class=" mt-2">
                            <button type="button" id="btnCheck"
                                class="btn submit-form-btn btn-block text-dark shadow">ตรวจสอบ</button>
                        </div>
                    </div>
                </div>

            </div>


        </div>
    </div>

</div>
</div>
@endsection


@section('scripts')
<script>
    $(document).ready(() => {
        var token = "{{ csrf_token() }}";

        $(".loadings").show();

        setTimeout(() => {
            $(".loadings").hide();
        }, 1000);

        function reset() {
            $('#formCheck').show();
            $('#formResult').hide();
            $('#phoneTracking').val('');
            $("#btnCheck").attr("disabled", true);
            $('#resultFail').hide();
        }

        $(document).on('click', '#trakingBtn', (event) => {
            $("#checkTraking").modal("show");
            reset();
        })

        $(document).on('click', '#termsAndConditions', (event) => {
            $("#termModal").modal("show");
        })

        $(document).on('click', '#registerBtn', function (event) {
            window.location.href = "{{ route('register')}}";
        })

        $("#btnCheck").attr("disabled", true);
        $('#formResult').hide();

        $("#phoneTracking").keyup(function () {
            let phoneTk = $("#phoneTracking").val();
            if (phoneTk && phoneTk.length == 10) {
                $("#btnCheck").attr("disabled", false);
            } else {
                $("#btnCheck").attr("disabled", true);
            }
        });

        $('.close-modal-btn').click(() => {
            reset()
        })



        $("#btnCheck").click(() => {
            $("#btnCheck").attr("disabled", true);

            $.ajax({
                headers: {
                    'x-csrf-token': token
                },
                method: 'POST',
                url: "{{ url('/') }}/check-traking",

                data: {
                    'phone': $("#phoneTracking").val()
                },
                success: function (response) {
                    if (response) {
                        if (response.status) {
                            $('#formCheck').hide();
                            $('#formResult').show();
                            $('#resultName').text('คุณ : ' + response.fullname);
                            $('#resultPhone').text('เบอร์โทร : ' + response.phone);
                            if (response.tracking) {
                                $('#resultTracking').text('เลขพัสดุ : ' + response.tracking)
                                $('#resultTracking').append( `
                                <br/>
                                <div class="mt-4" > 
                                <a 
                                target="_blank"
                                href="https://www.shippop.com/tracking?typeid=domestic&tracking_code=${response.tracking}">ติดตามพัสดุ </a>
                            </div>
                                ` );
                            } else {
                                $('#resultTracking').text('เลขพัสดุ : กำลังดำเนินการ')
                            }

                            $('#phoneTracking').val('');
                            $("#btnCheck").attr("disabled", true);
                            $('#resultFail').hide();

                        } else {
                            $('#formCheck').show();
                            $('#formResult').hide();
                            $('#resultFail').show();
                            $('#resultFail').text(
                                'ไม่พบข้อมูล กรุณาลองเบอร์โทรใหม่อีกครั้ง');
                            $("#btnCheck").attr("disabled", false);

                        }


                    }
                }
            })
        })

    })

</script>


@endsection

resources/views/customers/list.blade.php
@extends('layouts.main') @section('pageTitle') จัดการข้อมูลผู้สมัคร @endsection
@section('style') @endsection @section('content')

<div class="card mt-5">
    <div class="card-body">
        <h3 class="card-title">จัดการข้อมูลผู้สมัคร</h3>
        @if ($message = Session::get('success'))
        <div class=" alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>	
            <strong>{{ $message }}</strong>
        </div>
        @endif
        @if ($notification = Session::get('error'))
        <div class="alert alert-danger alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>	
                <strong>{{ $notification }}</strong>
        </div>
        @endif

        <div class="p-2">
            <div class="row">
                <div class="col-md-6">
                    <form action="{{ route('import') }}" method="POST" 
               class="mb-5"
                    enctype="multipart/form-data">
                        @csrf
                        <div class="form-group " >
                        <input type="file" name="file"  accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                        <button class="btn btn-success">Import File Excel</button>
                       <a href="{{route('export')}}" class="btn btn-outline-primary"> <i class="fas fa-file-excel"></i> Export File Excel</a>

                        </div>
                    </form>

                    <label class="font-weight-bold">ตั้งค่า limit จำนวนรับสมัคร</label>

                    <form action="{{ route('config.update') }}" method="POST"   class="form-inline">
                        @csrf

                        <div class="form-group">
                            <input type="hidden" name="id"  class="form-control" value="{{old('id',$config->id)}}"> 

                            <input type="text" name="limit_register"   value="{{old('limit_register',$config->limit_register)}}" class="form-control"> 
                        </div>
                            <button type="submit" class="btn btn-primary pl-2">อัพเดทการตั้งค่า</button>
                    </form>


                </div>
            </div>

        </div>
        <table class="table datatable-menagement display nowrap" style="width: 100%">
            <thead>
                <tr>
                    <!-- <th>#</th> -->
                    <th>ชื่อ - นามสกุล</th>
                    <th>เบอร์โทรศัพท์</th>
                    <th>ที่อยู่</th>
                    <th>รหัสไปรษณีย์</th>
                    <th>อายุ</th>
                    <th>เพศ</th>
                    <th>แคมเปญนี้จากสื่อ</th>
                    <th>เวลาสมัคร</th>
                    <th>หมายเลขพัสดุ</th>
                    <th>หมายเหตุ</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

@endsection @section('scripts')
<script>
    $(document).ready(() => {
        $(".loadings").hide();

        let table;

        table = $(".datatable-menagement").DataTable({
            processing: false,
            serverSide: true,
            pageLength: 100,
            ajax: {
                url: "{{ route('customers.getCustomersList') }}",
                dataType: "json",
                type: "POST",
                headers: {
                    "X-CSRF-TOKEN": "{{ csrf_token() }}",
                },
            },
            columns: [{
                    data: "fullname",
                    name: "fullname",
                    visible: true,
                },
                {
                    data: "phone",
                    name: "phone",
                    visible: true,
                },
                {
                    data: "address",
                    name: "address",
                    visible: true,
                    render: function (data, type, full, meta) {
                        return `<strong>ที่อยู่ :</strong> ${full.address} <br>
                      <strong>แขวง/ตำบล :</strong> ${full.tambon} 
                      <strong>อำเภอ/เขต :</strong> ${full.amphoe} 
                      <strong>จังหวัด :</strong> ${full.province} 
                      <strong>รหัสไปรษณีย์ :</strong> ${full.zipcode} `;
                    },
                },
                {
                    data: "zipcode",
                    name: "zipcode",
                    visible: true,
                },
                {
                    data: "age",
                    name: "age",
                    visible: true,
                    render: function (data, type, full, meta) {
                        let itemsAge = [
                            "น้อยกว่า 13 ปี",
                            "14 - 18 ปี",
                            "19 - 23 ปี",
                            "24 - 29 ปี",
                            "30 ปีขึ้นไป",
                        ];
                        return itemsAge[full.age];
                    },
                },
                {
                    data: "sex",
                    name: "sex",
                    visible: true,
                    render: function (data, type, full, meta) {
                        let itemsSex = ["ชาย", "หญิง", "ไม่ระบุ"];
                        return itemsSex[full.sex];
                    },
                },

                {
                    data: "sex",
                    name: "sex",
                    visible: true,
                    className: "text-center",

                    render: function (data, type, full, meta) {
                        let itemsMedianews = [
                            "Facebook",
                            "Youtube",
                            "Tiktok",
                            "Link",
                            "อื่นๆ",
                        ];
                        return full.medianews == 4 ? `อื่นๆ  ( ${full.medianews_other} )` :
                            itemsMedianews[full.medianews];
                    },
                },

                {
                    visible: true,
                    className: "text-left",
                    data: "created_at",
                    name: "created_at",
                    render: function (data, type, full, meta) {
                        return full.created_at;
                    },
                },
                {
                    visible: true,
                    data: "tracking",
                    name: "tracking",
                },
                {
                    visible: true,
                    className: "text-left",
                    render: function (data, type, full, meta) {
                        return "";
                    },
                },
                {
                    visible: true,
                    className: "text-left ",
                    render: function (data, type, full, meta) {
                        let btnDel = "";
                        let btnEdit = "";
                        let btn = "";

                        let urlDel = `{{ url('/') }}/customers/${full.id}/edit/`;

                        let urlEdit = `{{ url('/') }}/customers/${full.id}/edit/`;

                        btnEdit =
                            `<a class="link text-info"  href="${urlEdit}"><i class="fas fa-pen"></i> </a>`;
                        btnDel =
                            `<a class="link text-danger" id="Del" href="#" data-id="${full.id}" ><i class="fas fa-trash"></i> </a>`;
                        btn = `<div class="text-center">
                         
                            <div class="p-1">${btnEdit} ${btnDel} </div>
                           
                        </div>`;

                        return btn;
                    },
                },
            ],
        });


        $('.datatable-menagement').on('click', '#Del', function (e) {
            e.preventDefault();
            console.log('ok');
            Swal.fire({
                    title: '<strong>ต้องการลบข้อมูลหรือไม่ ?</strong>',
                    icon: 'info',
                    type: 'error',
                    icon: 'error',

                    showCloseButton: true,
                    showCancelButton: true,
                }

            ).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    let id = $('#Del').attr("data-id")
                    let urlDel = `{{ url('/') }}/customers/delete/${id}`;
                    window.location.href = urlDel;
                } else if (result.isDenied) {}
            })

        });


    });

</script>

@endsection

resources/views/customers/success.blade.php
@extends('layouts.page') 
@section('pageTitle') ลงทะเบียนกิจกรรมสำเร็จ
@endsection
@section('content') 
@php $action =route('customers.store');
@endphp

<form
    name="formRegister"
    id="formRegister"
    method="post"
    action="{{ $action }}"
>
    @csrf
    <div class="container">
        <div class="d-flex justify-content-center mt-5">
            <img
                src="{{ url('/img/logo.png') }}"
                class="img-logo"
                width="290px"
            />
        </div>
        <div class="page-register mt-3">
            <div class="card card-register shadow">
                <div class="card-body p-5">
                    <div class="text-center  " >
                        <i class="fas fa-box fa-5x text-color-pink-1"></i>
                        <div class="font-weight-bold h1 text-color-pink-1 mt-1"  >ความรักของคุณกำลังเดินทาง... <i class="fas fa-heart " style=" animation: heartbeat 1s infinite;"></i></div>

                        @if(Request::get('p'))
                        <div class="font-weight-bold mt-3"  >
                            <h3>คุณ {{ Request::get('p') }} </h3>
                        </div>
                        @endif
                    </div>
                </div>
            </div>

            <div class="mt-2 pb-4">
                  <div class="row justify-content-center">
                      <div class="col-md-4 mt-3 mt-lg-0 mt-md-0">
                        <button
                        type="button"
                        class="btn shadow index-form-btn  btn-block"
                        id="backIndex"
                    >
                       <i class="fas fa-home"></i>  กลับหน้าหลัก
                    </button>
                      </div>
                </div>
            </div>
        </div>
    </div>

    @section('scripts')
<script>
    $(document).ready(() => {
        let token = "{{ csrf_token() }}";
        $(document).on('click', '#backIndex', function(event) {
    window.location.href = "{{ route('customers.index')}}";
})

        $(".loadings").hide();

       

    })
</script>
@endsection